services:
    service:
        build:
            context: .
            dockerfile: dockerfile
        depends_on:
            db:
                condition: service_healthy
        environment:
            OUTCLIMB_DB_HOST: db
            OUTCLIMB_DB_NAME: outclimb
            OUTCLIMB_DB_USER: outclimb
            OUTCLIMB_DB_PASSWORD: change-this
            OUTCLIMB_REGISTRATION_SECRET: change-this
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://localhost:8080/ping']
            interval: 3s
            retries: 5
            start_period: 30s
        ports:
            - 8083:80

    db:
        command: '--default-authentication-plugin=mysql_native_password'
        environment:
            MARIADB_DATABASE: outclimb
            MARIADB_USER: outclimb
            MARIADB_PASSWORD: change-this
            MARIADB_RANDOM_ROOT_PASSWORD: true
        healthcheck:
            test: ['CMD-SHELL', 'mariadb-admin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD']
            interval: 3s
            retries: 5
            start_period: 30s
        image: mariadb
        restart: always
        volumes:
            - event-db-data:/var/lib/mysql

volumes:
    event-db-data:
